### ISSUE TITLE
Documentation on OpenAPI Specification

### ISSUE THREAD

**Issue by joelemanoel** [r00ta/maas-api-v3#1]
Hi @r00ta,

I would like to suggest that the new MAAS API v3 be documented in the OpenAPI Specification, this will help developers to have an easier time reading its documentation and understanding the requests.

Today the documentation is practically impossible to read and very confusing, as the requests are together, in addition to the descriptions being confusing.

**Comment by r00ta** [comment]
Hey @joelemanoel , 

Thank you for reaching out, I just love community contributions! I opened this repository to start playing around v3, as I personally see it as the baseline to build all the SDKs and the new CLI. 

The idea of this repository is to have a FastAPI that exposes some dummy endpoints just to automatically generate an openapi schema of v3. My idea is to properly design v3 with the focus on openapi, because I see it as the baseline to generate all the SDKs (Python - move away from python-libmaas, Typescript and so on ) and the new CLI. 

**Please note that this is a personal brainstorming repository** . If you want to keep an eye on this repo and provide some feedbacks, I would really appreciate!
